import { SystemDiscoveredSkill } from '../types';

export const DISCOVERED_SYSTEM_SKILLS: SystemDiscoveredSkill[] = [
  // GOOGLE ANTIGRAVITY PLUGINS & SKILLS (ACTUALLY INSTALLED ON LOCAL MACHINE)
  {
    id: 'sys-anti-1',
    name: 'android-cli-plugin',
    sourceSystem: 'Antigravity',
    path: 'file:///C:/Users/ahalliday/.gemini/config/plugins/android-cli-plugin',
    description: 'Android SDK management, project building, ADB device deployment, & Gradle diagnostics.',
    category: 'System Plugin',
    isInstalled: true,
    status: 'Active',
    version: '1.4.0',
  },
  {
    id: 'sys-anti-2',
    name: 'chrome-devtools-plugin',
    sourceSystem: 'Antigravity',
    path: 'file:///C:/Users/ahalliday/.gemini/config/plugins/chrome-devtools-plugin',
    description: 'Headless Chrome devtools automation, DOM element inspection, & page performance audit.',
    category: 'Browser',
    isInstalled: true,
    status: 'Active',
    version: '2.1.0',
  },
  {
    id: 'sys-anti-3',
    name: 'data-agent-kit-plugin',
    sourceSystem: 'Antigravity',
    path: 'file:///C:/Users/ahalliday/.gemini/config/plugins/data-agent-kit-plugin',
    description: 'Local vector search, SQLite data indexing, & structured JSON dataset extraction.',
    category: 'Database',
    isInstalled: true,
    status: 'Active',
    version: '1.1.2',
  },
  {
    id: 'sys-anti-4',
    name: 'firebase-plugin',
    sourceSystem: 'Antigravity',
    path: 'file:///C:/Users/ahalliday/.gemini/config/plugins/firebase',
    description: 'Firebase Firestore DB sync, authentication triggers, & cloud function deployment.',
    category: 'Database',
    isInstalled: true,
    status: 'Active',
    version: '3.0.1',
  },
  {
    id: 'sys-anti-5',
    name: 'google-antigravity-sdk',
    sourceSystem: 'Antigravity',
    path: 'file:///C:/Users/ahalliday/.gemini/config/plugins/google-antigravity-sdk',
    description: 'Core Antigravity subagent orchestration, tool routing, & sandbox terminal execution.',
    category: 'System Plugin',
    isInstalled: true,
    status: 'Active',
    version: '4.2.0',
  },
  {
    id: 'sys-anti-6',
    name: 'modern-web-guidance-plugin',
    sourceSystem: 'Antigravity',
    path: 'file:///C:/Users/ahalliday/.gemini/config/plugins/modern-web-guidance-plugin',
    description: 'Vite, React, Tailwind, HSL design system rules, & web accessibility standards.',
    category: 'Development',
    isInstalled: true,
    status: 'Active',
    version: '2.0.0',
  },

  // ANTHROPIC CLAUDE SKILLS & PLUGINS
  {
    id: 'sys-claude-1',
    name: 'Claude System Prompt & Artifacts Skill',
    sourceSystem: 'Claude',
    path: 'file:///C:/Users/ahalliday/.claude/skills/artifacts-engine',
    description: 'Generates interactive React artifacts, mermaid architectural diagrams, & markdown decks.',
    category: 'Intelligence',
    isInstalled: true,
    status: 'Active',
    version: '3.7.0',
  },
  {
    id: 'sys-claude-2',
    name: 'Claude Code Interpreter Plugin',
    sourceSystem: 'Claude',
    path: 'file:///C:/Users/ahalliday/.claude/plugins/code-interpreter',
    description: 'Executes Python pandas scripts, data visualizer charts, & SVG chart rendering.',
    category: 'Development',
    isInstalled: true,
    status: 'Active',
    version: '1.8.0',
  },

  // GOOGLE AI STUDIO & GEMINI SKILLS
  {
    id: 'sys-gemini-1',
    name: 'Gemini Multimodal Reasoning Skill',
    sourceSystem: 'Gemini',
    path: 'file:///C:/Users/ahalliday/.gemini/skills/multimodal-reasoning',
    description: 'Analyzes high-res UI screenshots, wireframes, PDF spec documents, & audio notes.',
    category: 'Intelligence',
    isInstalled: true,
    status: 'Active',
    version: '2.5.0',
  },
  {
    id: 'sys-studio-1',
    name: 'Google AI Studio Function Calling',
    sourceSystem: 'Google AI Studio',
    path: 'file:///C:/Users/ahalliday/.gemini/plugins/function-calling',
    description: 'Structured JSON schema output validation and REST API function execution.',
    category: 'System Plugin',
    isInstalled: true,
    status: 'Active',
    version: '1.3.0',
  },

  // CURSOR EDITOR SKILLS & PLUGINS
  {
    id: 'sys-cursor-1',
    name: 'Cursor .cursorrules Architecture Engine',
    sourceSystem: 'Cursor',
    path: 'file:///C:/Users/ahalliday/.cursor/rules/project-rules',
    description: 'Enforces project linting rules, component file structures, & strict type checking.',
    category: 'Development',
    isInstalled: true,
    status: 'Active',
    version: '0.42.0',
  },

  // CHATGPT & OPENAI PLUGINS
  {
    id: 'sys-gpt-1',
    name: 'ChatGPT Code Interpreter & Data Analysis',
    sourceSystem: 'ChatGPT',
    path: 'file:///C:/Users/ahalliday/.openai/plugins/code-interpreter',
    description: 'Jupyter notebook code runner, CSV data transformation, & statistics modeling.',
    category: 'Development',
    isInstalled: true,
    status: 'Active',
    version: '4.0.0',
  },

  // PERPLEXITY DEEP RESEARCH PLUGINS
  {
    id: 'sys-perpx-1',
    name: 'Perplexity Deep Research Engine',
    sourceSystem: 'Perplexity',
    path: 'file:///C:/Users/ahalliday/.perplexity/plugins/deep-research',
    description: 'Real-time web search citation engine with academic & industry paper summaries.',
    category: 'Intelligence',
    isInstalled: true,
    status: 'Active',
    version: '2.1.0',
  },
];
