#!/usr/bin/env node
/**
 * Emit Halliday CSS custom properties matching the executive dashboard tokens.
 * Usage: node halliday-brand-guide/scripts/generate-css.cjs [outfile]
 */
const fs = require('fs');
const path = require('path');

const css = `/* Generated by halliday-brand-guide/scripts/generate-css.cjs — do not hand-edit; regenerate */
:root {
  /* Core Palette */
  --color-primary-navy: #02295b;
  --color-primary-gold: #fda700;
  --color-primary-canvas: #d6d6d6;

  /* Secondary & Neutral Palette */
  --color-secondary-charcoal: #333f3f;
  --color-secondary-silver: #b0b5b3;
  --color-secondary-muted-fill: #d8d8d6;

  /* Functional UI Mappings */
  --bg-page: var(--color-primary-canvas);
  --bg-section-alt: var(--color-secondary-muted-fill);
  --text-heading: var(--color-primary-navy);
  --text-body: var(--color-secondary-charcoal);
  --text-muted: var(--color-secondary-silver);
  --border-subtle: var(--color-secondary-silver);
  --accent-cta: var(--color-primary-gold);

  /* Brand runtime (defaults; overridden by brandingService) */
  --brand-accent: #fda700;
  --brand-accent-secondary: #02295b;
  --brand-font: #02295b;
  --brand-font-secondary: #333f3f;
  --brand-on-accent: #02295b;
  --brand-on-secondary: #d6d6d6;
  --brand-button: #fda700;
  --brand-gradient: linear-gradient(135deg, #fda700, #02295b);
  --brand-gradient-x: linear-gradient(90deg, #fda700, #02295b);

  /* Semantic status — NEVER remapped by brand personalization */
  --status-critical: #e11d48;
  --status-warning: #f59e0b;
  --status-success: #059669;
}
`;

const out = process.argv[2]
  ? path.resolve(process.argv[2])
  : path.join(__dirname, '..', 'generated', 'halliday-tokens.css');

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, css, 'utf8');
console.log(`Wrote ${out}`);
